# Generated by Django 3.2.6 on 2021-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='00000000', max_length=10, unique=True, verbose_name='username'),
        ),
    ]
