# Generated by Django 3.2.6 on 2021-10-13 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 10, 52, 55, 279658)),
        ),
    ]
