# Generated by Django 3.2.6 on 2021-10-13 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 13, 2, 35, 590694)),
        ),
    ]
