# Generated by Django 3.2.6 on 2021-10-13 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employees_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='employees',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 13, 36, 32, 796733)),
        ),
    ]
