# Generated by Django 3.2.6 on 2021-10-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20211013_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_number',
            field=models.IntegerField(unique=True),
        ),
    ]
