# Generated by Django 3.2.6 on 2021-08-27 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('full_description', models.TextField()),
                ('cat_type', models.CharField(choices=[('Appliance', 'Appliance'), ('Carpentry', 'Carpentry'), ('Club House', 'Club House'), ('Common Area', 'Common Area'), ('Door Codes', 'Door Codes'), ('Doors/Windows', 'Doors/Windows'), ('Electrical', 'Electrical'), ('Flooring/Carpenting', 'Flooring/Carpenting'), ('Grounds', 'Grounds'), ('Laundry Rooms', 'Laundry Rooms'), ('Other', 'Other')], default='', max_length=40)),
                ('status', models.CharField(choices=[('New', 'New'), ('In-progress', 'In-progress'), ('Completed', 'Completed')], default='New', max_length=20)),
                ('loc_type', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Master Bathroom', 'Master Bathroom'), ('Master Bedroom', 'Master Bedroom'), ('Hallway', 'Hallway'), ('Patio', 'Patio'), ('Second Bedroom', 'Second Bedroom'), ('Foyer', 'Foyer'), ('Balcony', 'Balcony')], default='', max_length=40)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
